job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: taiwan
    CONTAINER_PREFIX: planet4-taiwan
    BASE_RELEASE: v25.19.0
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: taiwan
    HELM_RELEASE: planet4-taiwan
    WP_DB_NAME: planet4-taiwan_wordpress_develop
    WP_STATELESS_BUCKET: planet4-taiwan-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: taiwan-staging
    HELM_RELEASE: planet4-taiwan-release
    WP_DB_NAME: planet4-taiwan_wordpress_release
    WP_STATELESS_BUCKET: planet4-taiwan-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: taiwan
    HELM_RELEASE: planet4-taiwan-master
    MIN_REPLICA_COUNT: 2
    WP_DB_NAME: planet4-taiwan_wordpress_master
    WP_STATELESS_BUCKET: planet4-taiwan-stateless
